###
GET http://localhost:4001/v1/getAllUser
Content-Type: application/json

###
POST http://localhost:4001/v1/addUser
Content-Type: application/json

{
        "Username": "User1",
        "Password": "Password",
        "Firstname": "Cheryl",
        "Lastname": "Chia",
        "Email": "CherylChia@bestbank.com",
        "Address": "Block 567 Marina Bay Sands #63-743",
        "OptIntoPhyStatements": 1
}
###
POST http://localhost:4001/v1/login
Content-Type: application/json

{
    "Username": "PresidentDBS",
    "Password": "Multiplier3.5%"
}

###
POST http://localhost:4001/v1/editUser
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzAwNTM2NzcsInVzZXJpZCI6IlByZXNpZGVudERCUyIsImlhdCI6MTY3MDA1MzM3N30.gi3J_eYkIh6LBwEe06TpS_L0vBUn6ZDnctEmAs2AiKo

{
    "Username": "PresidentDBS",
    "Address": "Block 567 Marina Bay Sands #63-299",
    "Email": "CherylChia@bestbank.com"
}

