###
GET http://localhost:4001/v1/getUser
Content-Type: application/json

###
POST http://localhost:4001/v1/addUser
Content-Type: application/json

{
        "Username": "PresidentDBS",
        "Password": "Multiplier3.5%",
        "Firstname": "Cheryl",
        "Lastname": "Chia",
        "Email": "CherylChia@bestbank.com",
        "Address": "Block 567 Marina Bay Sands #63-743",
        "OptIntoPhyStatements": 1
}
###
POST http://localhost:4001/v1/login
Content-Type: application/json

{
    "Username": "PresidentDBS",
    "Password": "Multiplier3.5%"
}